(cl:defpackage dji_sdk-msg
  (:use )
  (:export
   "<FLIGHTANOMALY>"
   "FLIGHTANOMALY"
   "<GIMBAL>"
   "GIMBAL"
   "<MISSIONHOTPOINTTASK>"
   "MISSIONHOTPOINTTASK"
   "<MISSIONWAYPOINT>"
   "MISSIONWAYPOINT"
   "<MISSIONWAYPOINTACTION>"
   "MISSIONWAYPOINTACTION"
   "<MISSIONWAYPOINTTASK>"
   "MISSIONWAYPOINTTASK"
   "<MOBILEDATA>"
   "MOBILEDATA"
   "<VOPOSITION>"
   "VOPOSITION"
   "<WAYPOINT>"
   "WAYPOINT"
   "<WAYPOINTLIST>"
   "WAYPOINTLIST"
  ))

